### ISSUE TITLE
OFAC list migration

### ISSUE THREAD

**Issue by randomishwalk** [ultrasoundmoney/ofac-ethereum-addresses#1]
Is it worth putting [this readme file](https://github.com/ultrasoundmoney/ofac-ethereum-addresses/blob/main/README.md) into a db form via something like Google Sheets (on the low end of functionality) and something like Airtable (on the high end of functionality)?

Just thinking it would be easier to maintain in that format over time. Thoughts? I'm happy to help set up if Airtable--can do it pretty easily via something like their "submission forms" feature (and have the appropriate checks on new db record entries) and think can mostly be done via their free version with some modifications and thoughtful setup

**Comment by JustinDrake** [comment]
I added a CSV [here](https://github.com/ultrasoundmoney/ofac-ethereum-addresses/blob/main/data.csv)! 😄 Github natively provides search functionality for it.

I'm not familiar with Airtable—feel free to submit a PR if you think it's valuable :)

**Comment by randomishwalk** [comment]
I may spin something up that'll make maintenance of this easier and help with crowdsourcing the effort. Let's see what the extent of volume looks like when it comes to OFAC SDN list updates/revisions

**Comment by randomishwalk** [comment]
I'll keep this issue open for a little bit so I can remember to do this when relevant. Does that work @JustinDrake?

**Comment by JustinDrake** [comment]
Chris Meisl from Blocknative kindly pointed me to [this repo](https://github.com/0xB10C/ofac-sanctioned-digital-currency-addresses). It may be worth comparing the output of that repo with this list.
